Update centronic-stick.py
I'm using the Centronic controller inside a docker container (python-slim) and get the following message almost daily:
OSError: [Errno 24] Too many open files: '/tmp/centronic-stick.lock'
I suspect that it is because the file is not closed again (see line 457).